*       *********************************************************
*       * 09.05.2005           GRIDMENU.MPR             00:23:18
*       *********************************************************
*       * Author''s Name
*       *
*       * Copyright (C) 2005 Company Name
*       * Address
*       * City,     Zip
*       *
*       * Description:
*       * This PROGRAM was automatically generated BY GENMENU.
*       *********************************************************

&& передать Column, который вызывает иеню
lparameters oCol
private oGrd, lFindAcces, lFilterAcces
local lAcces as Logical, oHead as Header, lnRecFunc

&& получить ГРИД-источник
oGrd = oCol.Parent
for each oHead in oCol.Objects 
	if oHead.BaseClass = 'Header'
		exit
	endif
next

lnRecFunc = 0 + Iif(Sys(1269,oGrd,[RecAdd],0),1,0)
lnRecFunc = lnRecFunc + Iif(Sys(1269,oGrd,[RecUpdate],0),2,0)
lnRecFunc = lnRecFunc + Iif(Sys(1269,oGrd,[RecDelete],0),4,0)

&& определить доступ к меню поиска (в BLOB полях искать нельзя) и
&& доступ к фильтру
lFindAcces = .T.
lFilterAcces = .T.
lAcces = Empty(oCol.ControlSource)
if !lAcces
	lAcces = !InList(Vartype(Evaluate(oCol.ControlSource)),'C','D','T','N','Y','L') or ;
		oGrd.ActiveRow = 0
	lFindAcces = lAcces or !oGrd.RecFind_Flag
	lFilterAcces = lAcces or !oGrd.RecFilter_Flag
endif

*       *********************************************************
*       *                      Menu Definition
*       *********************************************************
*

DEFINE POPUP shortcut SHORTCUT RELATIVE FROM MROW(),MCOL()
DEFINE BAR 1 OF shortcut PROMPT "\<Нет" ;
	KEY ALT+C, "" ;
	SKIP FOR oGrd.ActiveRow = 0 ;
	PICTURE Iif(oCol.SortState=0,_screen.__lstImgCheck.Picture,_screen.__lstImgEmpt.Picture);
	MESSAGE "Сортировка ["+oHead.Caption+"] отсутствует"
DEFINE BAR 2 OF shortcut PROMPT "\<Возрастание" ;
	KEY ALT+D, "" ;
	SKIP FOR oGrd.ActiveRow = 0 ;
	PICTURE Iif(oCol.SortState=1,_screen.__lstImgCheck.Picture,_screen.__lstImgEmpt.Picture);
	MESSAGE "Сортировать ["+oHead.Caption+"] по возрастанию"
DEFINE BAR 3 OF shortcut PROMPT "\<Убывание" ;
	KEY ALT+E, "" ;
	SKIP FOR oGrd.ActiveRow = 0 ;
	PICTURE Iif(oCol.SortState=2,_screen.__lstImgCheck.Picture,_screen.__lstImgEmpt.Picture);
	MESSAGE "Сортировать ["+oHead.Caption+"] по убыванию"
DEFINE BAR 4 OF shortcut PROMPT "\-"

if Bitand(lnRecFunc,1)>0
	DEFINE BAR 5 OF shortcut PROMPT "Д\<обавить" ;
		PICTURE "D:\JokerClasses\For VFP_9\Bricksimage_buttons\bappend.bmp" ;
		MESSAGE [Добавить новую запись]
endif
if Bitand(lnRecFunc,2)>0
	DEFINE BAR 6 OF shortcut PROMPT "\<Изменить" ;
		SKIP FOR oGrd.ActiveRow = 0 ;
		PICTURE "D:\JokerClasses\For VFP_9\Bricks\image_buttons\bupdate.bmp" ;
		MESSAGE [Редактировать текущую запись]
endif
if Bitand(lnRecFunc,4)>0
	DEFINE BAR 7 OF shortcut PROMPT "У\<далить" ;
		SKIP FOR oGrd.ActiveRow = 0 ;
		PICTURE "D:\JokerClasses\For VFP_9\Bricks\image_buttons\bremove.bmp" ;
		MESSAGE [Удалить выделенную запись]	
endif

if lnRecFunc>0
	DEFINE BAR 8 OF shortcut PROMPT "\-"
endif

DEFINE BAR 9 OF shortcut PROMPT "\<Поиск..." ;
	KEY ALT+G, "" ;
	SKIP FOR lFindAcces ;
	PICTURE "D:\JokerClasses\For VFP_9\Bricks\icons_menu\bfind.bmp" ;
	MESSAGE "Поиск значения в ["+oHead.Caption+"]"
DEFINE BAR 10 OF shortcut PROMPT "\<Фильтр по текущему" ;
	KEY ALT+A, "" ;
	SKIP FOR lFilterAcces ;
	PICTURE "D:\JokerClasses\For VFP_9\Bricks\image_buttons\bfiltrcurrent.bmp" ;
	MESSAGE "Фильтрация по выбранному значению в ["+oHead.Caption+"]"

ON SELECTION BAR 1 OF shortcut oGrd.Sorting(oCol,0)
ON SELECTION BAR 2 OF shortcut oGrd.Sorting(oCol,1)
ON SELECTION BAR 3 OF shortcut oGrd.Sorting(oCol,2)

if Bitand(lnRecFunc,1)>0
	on selection bar 5 of shortcut oGrd.RecAdd()
endif 
if Bitand(lnRecFunc,2)>0
	on selection bar 6 of shortcut oGrd.RecUpdate()
endif 
if Bitand(lnRecFunc,4)>0
	on selection bar 7 of shortcut oGrd.Recdelete()
endif 

ON SELECTION BAR 9 OF shortcut oGrd.RecFind(oHead)
ON SELECTION BAR 10 OF shortcut oGrd.RecFilterOne(oCol)

ACTIVATE POPUP shortcut
